" gvim/MacVim configuration file

if has('win32') || has('win64')
	set guifont="Inconsolata":h12:cEASTEUROPE
	source $VIMRUNTIME/mswin.vim
else
	set guifont=Literation\ Mono\ Powerline:h12
	let g:airline_powerline_fonts=1
endif

set guioptions-=M
set guioptions-=T

set lines=40 columns=122
