" gvim/MacVim configuration file

if has('win32') || has('win64')
	set guifont="Inconsolata":h12:cEASTEUROPE
	source $VIMRUNTIME/mswin.vim
else
	set guifont=Menlo\ Regular:h12
endif

set guioptions-=M
set guioptions-=T

set lines=40 columns=122
