## Variable definitions
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# reduce vi-key escape timeout
export KEYTIMEOUT=1

# less config
highlight_cmd=`which highlight`
if [[ $? -eq 0 ]]
then
	export LESSOPEN="| $highlight_cmd --failsafe --quiet --out-format=xterm256 %s"
fi
export LESS=' -R '

## / end of variables

# zgen - zsh plugin manager and init file generator
source $HOME/dotfiles/zsh/zgen/zgen.zsh

# check if there's no init script
if ! zgen saved; then
	echo "Creating a zgen save"

	zgen oh-my-zsh

	## NOTE: after modifying this list of plugins, run "zgen update",
	## and then restart your zsh shell twice: first one executes this block
	## of code, second one initializes zsh properly.

	# plugins
	zgen oh-my-zsh plugins/git
	zgen oh-my-zsh plugins/git-prompt
	zgen oh-my-zsh plugins/git-remote-branch
	zgen oh-my-zsh plugins/brew
	zgen oh-my-zsh plugins/sudo
	zgen oh-my-zsh plugins/symfony2
	zgen oh-my-zsh plugins/command-not-found
	zgen oh-my-zsh plugins/aws
	zgen oh-my-zsh plugins/colored-man-pages
	zgen load zsh-users/zsh-syntax-highlighting
	zgen load zsh-users/zsh-history-substring-search

	# completions
	zgen load zsh-users/zsh-completions src

	# save all to init script
	zgen save
fi

setopt appendhistory extendedglob
unsetopt autocd beep nomatch notify
bindkey -v
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit && compinit

# bash-style word separators
autoload -U select-word-style
select-word-style bash

# bind UP and DOWN arrow keys, bind k and j for VI mode
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

## Keyboard shortcuts
# backspace
bindkey "^?" backward-delete-char
# ctrl+h
bindkey "^H" backward-delete-char
# ctrl+w
bindkey "^W" backward-kill-word
# ctrl+u
bindkey "^U" backward-kill-line

# numpad enter...
bindkey -s "^[OM" "^M"

autoload -U colors
colors
# prompt
# "%{$fg_bold[green]%}%m %{$fg_bold[white]%}%~ %(0?.$fg_bold[green].$fg_bold[red])%?$reset_color %{$fg_bold[yellow]%}%(\!.#.%%) $reset_color"
fbk="%{$fg_bold[black]%}"
fre="%{$fg_bold[red]%}"
fgr="%{$fg_bold[green]%}"
fye="%{$fg_bold[yellow]%}"
fbl="%{$fg_bold[blue]%}"
fma="%{$fg_bold[magenta]%}"
fcy="%{$fg_bold[cyan]%}"
fwh="%{$fg_bold[white]%}"
rst="%{$reset_color%}"

prompt=""
# hostname
prompt+="%(0#,$fre,$fgr)%n$fgr@%m$rst "

# path
prompt+="$fbl%5~$rst "

# exit code of last command
prompt+="%(0?,,$fre%?$rst )"

# prompt symbol
prompt+="%(!.$fcy#.$fye%%)$rst "

export PROMPT

## OS-specific configuration and overrides
if [[ `uname` == 'Linux' ]]
then
	export LINUX=1
	ZSH_LINUX=$HOME/.zshrc.linux.zsh
	if [[ -f $ZSH_LINUX ]]
	then
		source $ZSH_LINUX
	fi
else
	export LINUX=
fi

if [[ `uname` == 'Darwin' ]]
then
	export OSX=1
	ZSH_OSX=$HOME/.zshrc.osx.zsh
	if [[ -f $ZSH_OSX ]]
	then
		source $ZSH_OSX
	fi
else
	export OSX=
fi

alias tcol256="terminal-colors --cube-slice --numbers --padding"
alias grrep="grep -i -r"
